name: Continuous Delivery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Simulando Build
      run: echo "O build foi um sucesso!"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Simulando Deploy
      run: echo "O deploy foi um sucesso!"
