name: Continuous Delivery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: echo "Rodando todos os testes..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Application
      run: echo "Fazendo o Deploy com sucesso!"
